SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 850
CELL_SIZE = 30

GRID_WIDTH = SCREEN_WIDTH // CELL_SIZE   
GRID_HEIGHT = SCREEN_HEIGHT // CELL_SIZE 

WIDTH_MARGIN = SCREEN_WIDTH - (CELL_SIZE * GRID_WIDTH)
HEIGHT_MARGIN = SCREEN_HEIGHT - (CELL_SIZE * GRID_HEIGHT)

X_OFFSET = WIDTH_MARGIN // 2
Y_OFFSET = HEIGHT_MARGIN // 2

UI_ROWS = 4

MAZE_WIDTH = 27 * CELL_SIZE
MAZE_START_X = -MAZE_WIDTH / 2 + CELL_SIZE / 2
MAZE_START_Y = SCREEN_HEIGHT / 2 - (UI_ROWS * CELL_SIZE) - CELL_SIZE / 2

#now for pacman and mob
PACMAN_MOVE_SPEED = 8

ENEMY_MOVE_SPEED = 5

